---
kind: pipeline
type: docker
name: Linting

concurrency:
  limit: 1

steps:
  - name: Shellcheck
    image: koalaman/shellcheck-alpine
    commands:
    - ./test/shellcheck.sh
  - name: PHP 8.1
    image: php:8.1-cli-bullseye
    commands:
      - ./test/check_php.sh ./web/

trigger:
      event: [ pull_request, push ]
      ref:
      - refs/heads/staging/*
      - refs/heads/beta
      - refs/heads/release
      - refs/heads/main
      - refs/pull/*/head


---
kind: signature
hmac: 4eec34ee92f63737d6a976140e6e54adf637ebbb4836b17a083c560a4440c54f