#!/bin/bash

set -e

if [ "$1" != "configure" ]; then
	exit 0
fi

# Run triggers only on updates
if [ ! -e "/usr/local/devcp/data/users/" ]; then
	exit
fi

# Prevent running and causes issues with outdated devcp version
if ! id "hestiaweb" &> /dev/null; then
	exit
fi

# Touch and set permisions on default log files on installation
update-rc.d devcp defaults > /dev/null
invoke-rc.d devcp start || true

# Adapt Port Listing in HESTIA NGINX Backend
source /usr/local/devcp/func/syshealth.sh # Load syshealth functions

# Check if the function syshealth_adapt_hestia_nginx_listen_ports exists
if ! declare -f syshealth_adapt_hestia_nginx_listen_ports > /dev/null; then
	exit
fi
syshealth_adapt_hestia_nginx_listen_ports # Adapt port listing
syshealth_adapt_nginx_resolver

###############################################################
#                Initialize functions/variables               #
###############################################################

if [ -z "$HESTIA" ]; then
	export HESTIA='/usr/local/devcp'
	PATH=$PATH:/usr/local/devcp/bin
	export PATH
fi

# Check if preinstall hook exists
if [ -e "/etc/hestiacp/hooks/nginx/pre_install.sh" ]; then
	/etc/hestiacp/hooks/nginx/pre_install.sh
fi

# Load upgrade functions and variables
source /usr/local/devcp/func/main.sh
source /usr/local/devcp/func/upgrade.sh
source /usr/local/devcp/conf/devcp.conf
source /usr/local/devcp/install/upgrade/upgrade.conf

# Reset backend port
if [ -n "$BACKEND_PORT" ]; then
	/usr/local/devcp/bin/v-change-sys-port $BACKEND_PORT
fi

if [ -e "/etc/hestiacp/hooks/nginx/post_install.sh" ]; then
	/etc/hestiacp/hooks/nginx/post_install.sh
fi

# Restart devcp service
if [ -f "/etc/init.d/devcp" ]; then
	systemctl restart devcp > /dev/null 2>&1
fi
