#!/bin/sh

set -e

if [ "$1" != "configure" ]; then
    exit 0
fi

# Touch and set permisions on default log files on installation
update-rc.d hestia defaults >/dev/null
invoke-rc.d hestia start || true
