#!/bin/bash

###############################################################
#                Initialize functions/variables               #
###############################################################
source /usr/local/hestia/conf/hestia.conf
source /usr/local/hestia/func/main.sh
source /usr/local/hestia/func/upgrade.sh

###############################################################
#             Set new version numbers for packages            #
###############################################################
# Hestia Control Panel
new_version=$(dpkg -l | awk '$2=="hestia" { print $3 }')

# phpMyAdmin
pma_v='4.9.0.1'

###############################################################
#               Begin standard upgrade routines               #
###############################################################

# Initialize backup directories
upgrade_init_backup

# Set up console display and welcome message
clear
upgrade_welcome_message

# Execute version-specific upgrade scripts
upgrade_start_routine

# Upgrade phpMyAdmin if applicable
upgrade_phpmyadmin

# Set new version number in hestia.conf
upgrade_set_version

# Perform account and domain rebuild to ensure configuration files are correct
upgrade_rebuild_users

# Restart necessary services for changes to take full effect
upgrade_restart_services

# Add upgrade notification to admin user's panel and display completion message
upgrade_complete_message

exit 0
