#!/bin/bash

# Run triggers only on updates
if [ ! -e "/usr/local/hestia/data/users/admin" ]; then
    exit
fi

# Load hestia.conf
source /usr/local/hestia/conf/hestia.conf

# Get hestia version
version=$(dpkg -l | awk '$2=="hestia" { print $3 }')

# Set hestia version if different.
if [ "$VERSION" != "$version" ]; then
    sed -i "s/VERSION='$VERSION'/VERSION='$version'/g" /usr/local/hestia/conf/hestia.conf
fi