#!/bin/bash

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        if test "x$1" == "xpurge"
        then
            userdel -r sogo || true
            rm -rf /var/spool/sogo
            rm -rf /var/log/sogo
            rm -rf /var/run/sogo
        fi
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0
esac

# Automatically added by dh_installinit/11.1.6ubuntu2
if [ "$1" = "purge" ] ; then
	update-rc.d sogo remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0
