#!/bin/bash

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see /usr/share/doc/packaging-manual/

# Automatically added by dh_installinit/11.1.6ubuntu2
if [ -x "/etc/init.d/sogo" ] && [ "$1" = remove ]; then
	invoke-rc.d sogo stop || exit 1
fi
# End automatically added section


exit 0
