#!/bin/bash

set -e

if [ "$1" != "configure" ]; then
	exit 0
fi

# Run triggers below only on updates
if [ ! -e "/usr/local/devcp/data/users/" ]; then
	exit
fi

# Prevent running and causes issues with outdated devcp version
if ! id "hestiaweb" &> /dev/null; then
	exit
fi

# Check if preinstall hook exists
if [ -e "/etc/hestiacp/hooks/php/pre_install.sh" ]; then
	/etc/hestiacp/hooks/php/pre_install.sh
fi

###############################################################
#                Initialize functions/variables               #
###############################################################

if [ -z "$HESTIA" ]; then
	export HESTIA='/usr/local/devcp'
	PATH=$PATH:/usr/local/devcp/bin
	export PATH
fi

# Load upgrade functions and variables
source /usr/local/devcp/func/main.sh
source /usr/local/devcp/func/upgrade.sh
source /usr/local/devcp/conf/devcp.conf
source /usr/local/devcp/install/upgrade/upgrade.conf

# Restart devcp service
if [ -f "/etc/init.d/devcp" ]; then
	systemctl restart devcp > /dev/null 2>&1
fi

# Check if preinstall hook exists
if [ -e "/etc/hestiacp/hooks/php/post_install.sh" ]; then
	/etc/hestiacp/hooks/php/post_install.sh
fi
