#!/bin/bash

if [ -e /usr/local/vesta/softaculous/vesta_install.inc ]; then
    if [ ! -e /usr/local/vesta/softaculous/conf/count.json ]; then
        cd /usr/local/vesta/softaculous
        /usr/local/vesta/php/bin/php vesta_install.inc
        rm vesta_install.inc
    fi
fi

exit 0
