# Fail2Ban configuration file for hestia IPv6

[Definition]

actionstart = /usr/local/hestia/bin/v-add-firewall-chain-ipv6 <name>
actionstop = /usr/local/hestia/bin/v-delete-firewall-chain-ipv6 <name>
actioncheck = ip6tables -n -L INPUT | grep -q 'fail2ban-<name>[ \t]'
actionban = /usr/local/hestia/bin/v-add-firewall-ban-ipv6 <ip> <name>
actionunban = /usr/local/hestia/bin/v-delete-firewall-ban-ipv6 <ip> <name>
