# Fail2Ban configuration file for hestia

[Definition]

actionstart = /usr/bin/flock -w 30 /run/hestia-firewall.lock /usr/local/hestia/bin/v-add-firewall-chain <name>
actionstop = /usr/bin/flock -w 30 /run/hestia-firewall.lock /usr/local/hestia/bin/v-delete-firewall-chain <name>
actioncheck = /usr/sbin/iptables -n -L INPUT | grep -q 'fail2ban-<name>[ \t]'
actionban = /usr/bin/flock -w 30 /run/hestia-firewall.lock /usr/local/hestia/bin/v-add-firewall-ban <ip> <name>
actionunban = /usr/bin/flock -w 30 /run/hestia-firewall.lock /usr/bin/env HESTIA_F2B_CALLER=1 /usr/local/hestia/bin/v-delete-firewall-ban <ip> <name>
