# Fail2Ban configuration file for hestia

[Definition]

actionstart = flock -w 30 /run/hestia-firewall.lock /usr/local/hestia/bin/v-add-firewall-chain <name>
actionstop = flock -w 30 /run/hestia-firewall.lock /usr/local/hestia/bin/v-delete-firewall-chain <name>
actioncheck = iptables -n -L INPUT | grep -q 'fail2ban-<name>[ \t]'
actionban = flock -w 30 /run/hestia-firewall.lock /usr/local/hestia/bin/v-add-firewall-ban <ip> <name>
actionunban = flock -w 30 /run/hestia-firewall.lock env HESTIA_F2B_CALLER=1 /usr/local/hestia/bin/v-delete-firewall-ban <ip> <name>
