#!/bin/bash

# DevIT Control Panel upgrade script for target version 1.3.3

#######################################################################################
#######                      Place additional commands below.                   #######
#######################################################################################

# Check if keys folder exists and adjust permissions
if [ -d "$DevIT/data/keys" ]; then
	echo '[ * ] Update permissions'
	chmod 750 "$DevIT/data/keys"
	chown admin:root "$DevIT/data/keys"
fi

if [[ ! -e /etc/DevITcp/DevIT.conf ]]; then
	echo '[ * ] Create global DevIT config'

	mkdir -p /etc/DevITcp
	echo -e "# Do not edit this file, will get overwritten on next upgrade, use /etc/DevITcp/local.conf instead\n\nexport DevIT='/usr/local/DevIT'\n\n[[ -f /etc/DevITcp/local.conf ]] && source /etc/DevITcp/local.conf" > /etc/DevITcp/DevIT.conf
fi
