#!/bin/sh

### BEGIN INIT INFO
# Provides:          hestia-web-terminal
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the websocket server for the hestiacp web terminal
# Description:       starts a node server.js using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

WEB_TERMINAL_DAEMON=/usr/local/hestia/web-terminal/server.js
WEB_TERMINAL_NAME=hestia-web-terminal
WEB_TERMINAL_DESC=hestia-web-terminal
WEB_TERMINAL_PID=/run/hestia-web-terminal.pid

set -e

. /lib/lsb/init-functions

. /etc/profile.d/hestia.sh

start_web_terminal() {
	start-stop-daemon --start --quiet --pidfile $WEB_TERMINAL_PID \
		--retry 5 --exec $WEB_TERMINAL_DAEMON --oknodo
}

stop_web_terminal() {
	start-stop-daemon --stop --quiet --pidfile $WEB_TERMINAL_PID \
		--retry 5 --oknodo --exec $WEB_TERMINAL_DAEMON
}

case "$1" in
	start)
		log_daemon_msg "Starting $WEB_TERMINAL_DESC" "$WEB_TERMINAL_NAME"
		start_web_terminal
		log_end_msg $?
		;;

	stop)
		log_daemon_msg "Stopping $WEB_TERMINAL_DESC" "$WEB_TERMINAL_NAME"
		stop_web_terminal
		log_end_msg $?
		;;

	restart | force-reload | reload | configtest | testconfig)
		log_daemon_msg "Restarting $WEB_TERMINAL_DESC" "$WEB_TERMINAL_NAME"
		stop_web_terminal
		sleep 1
		start_web_terminal
		log_end_msg $?
		;;

	status)
		status_of_proc -p $WEB_TERMINAL_PID "$WEB_TERMINAL_DAEMON" hestia-web-terminal
		;;

	*)
		echo "Usage: hestia-web-terminal {start|stop|restart|status}" >&2
		exit 1
		;;
esac

exit 0
