#!/bin/bash

set -e

if [ "$1" != "configure" ]; then
	exit 0
fi

# Run triggers below only on updates
if [ ! -e "/usr/local/hestia/data/users/admin" ]; then
	exit
fi

###############################################################
#                Initialize functions/variables               #
###############################################################

if [ -z "$HESTIA" ]; then
	export HESTIA='/usr/local/hestia'
	PATH=$PATH:/usr/local/hestia/bin
	export PATH
fi

# Load upgrade functions and variables
source /usr/local/hestia/func/main.sh
source /usr/local/hestia/func/upgrade.sh
source /usr/local/hestia/conf/hestia.conf
source /usr/local/hestia/install/upgrade/upgrade.conf

# Restart hestia-web-terminal service if enabled
if [ -f "/etc/systemd/system/hestia-web-terminal.service" ]; then
	systemctl daemon-reload > /dev/null 2>&1
	if systemctl is-enabled hestia-web-terminal > /dev/null 2>&1; then
		systemctl restart hestia-web-terminal
	fi
fi
