#!/bin/bash

set -e

if [ "$1" != "configure" ]; then
	exit 0
fi

# Run triggers below only on updates
if [ ! -e "/usr/local/devcp/data/users/admin" ]; then
	exit
fi

###############################################################
#                Initialize functions/variables               #
###############################################################

if [ -z "$HESTIA" ]; then
	export HESTIA='/usr/local/devcp'
	PATH=$PATH:/usr/local/devcp/bin
	export PATH
fi

# Load upgrade functions and variables
source /usr/local/devcp/func/main.sh
source /usr/local/devcp/func/upgrade.sh
source /usr/local/devcp/conf/devcp.conf
source /usr/local/devcp/install/upgrade/upgrade.conf

# Restart devcp-web-terminal service if enabled
if [ -f "/etc/systemd/system/devcp-web-terminal.service" ]; then
	systemctl daemon-reload > /dev/null 2>&1
	if systemctl is-enabled devcp-web-terminal > /dev/null 2>&1; then
		systemctl restart devcp-web-terminal
	fi
fi
